import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useState, useEffect } from "react"; // Import useState and useEffect hooks
import Header from "../components/header";
import LoggedIn from "../components/loggedIn";
import ShowPrice from "../components/showprice";
import { useAccount } from "wagmi";
import TransactionMonitor from "../components/TransactionMonitor";

export default function Home() {
  const { isConnected } = useAccount();
  const [isLoggedIn, setIsLoggedIn] = useState(false);

  useEffect(() => {
    if (isConnected) {
      setIsLoggedIn(true);
    } else {
      setIsLoggedIn(false);
    }
  }, [isConnected]);

  return (
    <section className={styles.container}>
      <Head>
        <title>Web 3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* Conditionally render the Header component */}
        {isLoggedIn && <Header >
          {/* <TransactionMonitor /> */}
        </Header>}
        <LoggedIn />
      </main>
    </section>
  );
}
